const store = new Map([
  ['V0', '24.8'],
  ['V1', '58.5'],
  ['V2', '0'],
  ['V3', '128'],
  ['V4', '3.82']
]);

export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') {
    res.statusCode = 200;
    return res.end();
  }

  const url = new URL(req.url, 'http://localhost');
  const path = url.pathname;
  const q = Object.fromEntries(url.searchParams);

  // 1. API: /api/blynk/update
  if (path.includes('update')) {
    if (q.pin && q.value !== undefined) store.set(q.pin.toUpperCase(), String(q.value));
    for (const [k, v] of Object.entries(q)) {
      if (/^[vVaAdD]\d+$/i.test(k)) store.set(k.toUpperCase(), String(v));
    }
    res.setHeader('Content-Type', 'application/json');
    res.statusCode = 200;
    return res.end(JSON.stringify({ success: true, status: 'ok', updated: q }));
  }

  // 2. API: /api/blynk/get
  if (path.includes('get')) {
    const pin = (q.pin || 'V0').toUpperCase();
    const val = store.get(pin) || '0';
    if (q.format === 'json') {
      res.setHeader('Content-Type', 'application/json');
      res.statusCode = 200;
      return res.end(JSON.stringify({ success: true, pin, value: val }));
    }
    res.setHeader('Content-Type', 'text/plain');
    res.statusCode = 200;
    return res.end(String(val));
  }

  // 3. API: /api/ai/query
  if (path.includes('query')) {
    const p = (q.prompt || '').toLowerCase();
    const act = [];
    if (p.includes('turn on relay') || p.includes('relay on')) {
      store.set('V2', '1');
      act.push({ pin: 'V2', value: '1', label: 'Relay 1 ON' });
    }
    if (p.includes('turn off relay') || p.includes('relay off')) {
      store.set('V2', '0');
      act.push({ pin: 'V2', value: '0', label: 'Relay 1 OFF' });
    }

    res.setHeader('Content-Type', 'application/json');
    res.statusCode = 200;
    return res.end(JSON.stringify({
      title: 'Telemetry Trend',
      description: 'Analysis generated by Blynk Alter AI',
      insights: `📊 Telemetry nominal. V0: ${store.get('V0')}°C, V1: ${store.get('V1')}%.`,
      actions: act,
      data: [
        { time: '10:00', temperature: 24.5, humidity: 58.0 },
        { time: '11:00', temperature: 25.2, humidity: 56.5 },
        { time: '12:00', temperature: 26.1, humidity: 54.0 }
      ]
    }));
  }

  res.statusCode = 404;
  res.end('Not Found');
}
const s=new Map([['V0','24.8'],['V1','58.5'],['V2','0'],['V3','128'],['V4','3.82']]);
export default function handler(q,r){
r.setHeader('Access-Control-Allow-Origin','*');
if(q.method==='OPTIONS')return r.end();
const u=new URL(q.url,'http://x'),p=u.pathname,v=Object.fromEntries(u.searchParams);
if(p.includes('update')){
if(v.pin)s.set(v.pin.toUpperCase(),String(v.value||'0'));
r.end(JSON.stringify({success:true}));
}else if(p.includes('get')){
r.end(s.get((v.pin||'V0').toUpperCase())||'0');
}else if(p.includes('query')){
r.end(JSON.stringify({title:'OK',insights:'V0:'+s.get('V0'),actions:[],data:[]}));
}else{r.statusCode=404;r.end('Not Found');}
}
